source "https://rubygems.org"

# Jekyll
gem "jekyll", "~> 4.2.1"

# Theme
gem "minimal-jekyll-theme"

# Local Theme Development
#gem "minimal-jekyll-theme", :path => "../"

# Plugins
group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-sitemap'
  gem 'jekyll-seo-tag'
  gem 'jekyll-archives'
end

# This Ruby 3.0.0 dependancy is needed until Jekyll V4.3.0 release
gem "webrick", "~> 1.7"
